language: python
python:
  - "2.7"
sudo: true

before_install:
  - git clone -b 3.2 https://github.com/antirez/redis vendor/redis
  - (cd vendor/redis; make && sudo make install)
  - echo -e '\n\n\n\n\n\n' | sudo ./vendor/redis/utils/install_server.sh

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run python setup.py test

after_success:
  - make -C docs html
  - ghp-import -n docs/_build/html
  - git push -fq https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages
